---
version: 2
updates:
  - package-ecosystem: docker
    directory: "/all-in-one"
    schedule:
      interval: daily
    reviewers:
      - "EasyDynamics/oscal-editor-reviewers"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    reviewers:
      - "EasyDynamics/oscal-editor-reviewers"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
